name: 'dbt_loads'
version: '1.0.0'
config-version: 2

profile: 'loadsmart'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
seed-paths: ["data"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_loads:
    staging:
      +materialized: view
      +tags: ["staging"]
      
    intermediate:
      +materialized: view
      +tags: ["intermediate"]
      
    semantic:
      +materialized: table
      +tags: ["semantic"]

on-run-start: "{{ log('Starting dbt run...', info=true) }}"
on-run-end: "{{ log('dbt run completed!', info=true) }}"