name: 'loadsmart'
version: '1.0.0'
config-version: 2

profile: 'loadsmart'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  loadsmart:
    staging:
      +materialized: view
      +tags: ["staging"]
      
    marts:
      +materialized: table
      +tags: ["marts"]

on-run-start: "{{ log('Starting dbt run...', info=true) }}"
on-run-end: "{{ log('dbt run completed!', info=true) }}"